using System.Text;

namespace DearStory.ProtocolGenerator;

/// <summary>Provides deterministic DearStory protocol model emitters.</summary>
public static class ModelEmitter
{
    /// <summary>Emits the generated C++ and C# model sources for a validated manifest.</summary>
    /// <param name="manifest">The manifest to transform into source code.</param>
    /// <returns>The generated source texts for both target languages.</returns>
    /// <exception cref="ArgumentNullException"><paramref name="manifest" /> is <see langword="null" />.</exception>
    public static GeneratedModels Emit(ProtocolManifest manifest)
    {
        ArgumentNullException.ThrowIfNull(manifest);
        return new GeneratedModels(EmitCpp(manifest), EmitCSharp(manifest));
    }

    private static string EmitCpp(ProtocolManifest manifest)
    {
        var lines = new List<string>
        {
            "// Generated by DearStory.ProtocolGenerator. Do not edit.",
            "#pragma once",
            string.Empty,
            "#include <cstdint>",
            "#include <optional>",
            "#include <string>",
            "#include <vector>",
            "#include <nlohmann/json.hpp>",
            string.Empty,
            "namespace dearstory::protocol::generated {",
            string.Empty
        };

        foreach (var enumDefinition in manifest.Enums.OrderBy(static item => item.Name, StringComparer.Ordinal))
        {
            lines.Add($"/// Represents the \"{enumDefinition.Name}\" generated enumeration.");
            lines.Add($"enum class {enumDefinition.Name} {{");
            foreach (var value in enumDefinition.Values)
            {
                lines.Add($"    {value},");
            }

            lines.Add("};");
            lines.Add(string.Empty);
        }

        foreach (var shape in EnumerateShapes(manifest))
        {
            lines.Add($"/// Represents the \"{shape.Name}\" generated model.");
            lines.Add($"struct {shape.Name} final {{");

            foreach (var field in shape.Fields.OrderBy(static item => item.Name, StringComparer.Ordinal))
            {
                lines.Add($"    /// Stores the value mapped from the \"{field.Name}\" wire field.");
                lines.Add($"    {ToCppType(field, manifest)} {field.Name}{{}};");
            }

            if (shape.Fields.Count > 0)
            {
                lines.Add(string.Empty);
            }

            lines.Add($"    friend bool operator==(const {shape.Name}&, const {shape.Name}&) = default;");
            lines.Add("};");
            lines.Add(string.Empty);
        }

        lines.Add("} // namespace dearstory::protocol::generated");
        return ToGeneratedText(lines);
    }

    private static string EmitCSharp(ProtocolManifest manifest)
    {
        var lines = new List<string>
        {
            "// Generated by DearStory.ProtocolGenerator. Do not edit.",
            "#nullable enable",
            string.Empty,
            "using System;",
            "using System.Collections.Generic;",
            "using System.Text.Json.Nodes;",
            "using System.Text.Json.Serialization;",
            string.Empty,
            "namespace DearStory.Protocol.Generated;",
            string.Empty
        };

        foreach (var enumDefinition in manifest.Enums.OrderBy(static item => item.Name, StringComparer.Ordinal))
        {
            var enumName = ToPascalCase(enumDefinition.Name);
            lines.Add("/// <summary>Represents the \"" + enumDefinition.Name + "\" generated enumeration.</summary>");
            lines.Add($"[JsonConverter(typeof(JsonStringEnumConverter<{enumName}>))]");
            lines.Add($"public enum {enumName}");
            lines.Add("{");
            foreach (var value in enumDefinition.Values)
            {
                lines.Add($"    /// <summary>Represents the \"{value}\" wire value.</summary>");
                lines.Add($"    [JsonStringEnumMemberName(\"{value}\")]");
                lines.Add($"    {ToPascalCase(value)},");
            }

            lines.Add("}");
            lines.Add(string.Empty);
        }

        foreach (var shape in EnumerateShapes(manifest))
        {
            var typeName = ToPascalCase(shape.Name);
            lines.Add($"/// <summary>Represents the \"{shape.Name}\" generated model.</summary>");
            lines.Add($"public sealed record {typeName}");
            lines.Add("{");

            foreach (var field in shape.Fields.OrderBy(static item => item.Name, StringComparer.Ordinal))
            {
                lines.Add($"    /// <summary>Gets or sets the value mapped from the \"{field.Name}\" wire field.</summary>");
                lines.Add($"    [JsonPropertyName(\"{field.Name}\")]");
                lines.Add($"    public {(field.Required ? "required " : string.Empty)}{ToCSharpType(field, manifest)} {ToPascalCase(field.Name)} {{ get; init; }}");
                lines.Add(string.Empty);
            }

            if (shape.Fields.Count > 0)
            {
                lines.RemoveAt(lines.Count - 1);
            }

            lines.Add("}");
            lines.Add(string.Empty);
        }

        return ToGeneratedText(lines);
    }

    private static IEnumerable<ShapeDefinition> EnumerateShapes(ProtocolManifest manifest)
    {
        foreach (var record in manifest.Records.OrderBy(static item => item.Name, StringComparer.Ordinal))
        {
            yield return new ShapeDefinition(record.Name, record.Fields);
        }

        foreach (var message in manifest.Messages.OrderBy(static item => item.Name, StringComparer.Ordinal))
        {
            yield return new ShapeDefinition(message.Name, message.Fields);
        }
    }

    private static string ToCppType(ManifestFieldDefinition field, ProtocolManifest manifest)
    {
        var baseType = ResolveCppType(field.Type, manifest);

        return field.Required ? baseType : $"std::optional<{baseType}>";
    }

    private static string ToCSharpType(ManifestFieldDefinition field, ProtocolManifest manifest)
    {
        var baseType = ResolveCSharpType(field.Type, manifest);

        if (field.Required)
        {
            return baseType;
        }

        return $"{baseType}?";
    }

    private static string ResolveCppType(string typeName, ProtocolManifest manifest)
    {
        if (typeName.EndsWith("[]", StringComparison.Ordinal))
        {
            return $"std::vector<{ResolveCppType(typeName[..^2], manifest)}>";
        }

        return typeName switch
        {
            "string" => "std::string",
            "uint16" => "std::uint16_t",
            "uuid" => "std::string",
            "object" => "nlohmann::json",
            "boolean" => "bool",
            "json" => "nlohmann::json",
            _ when manifest.Enums.Any(item => item.Name == typeName) => typeName,
            _ => typeName
        };
    }

    private static string ResolveCSharpType(string typeName, ProtocolManifest manifest)
    {
        if (typeName.EndsWith("[]", StringComparison.Ordinal))
        {
            return $"IReadOnlyList<{ResolveCSharpType(typeName[..^2], manifest)}>";
        }

        return typeName switch
        {
            "string" => "string",
            "uint16" => "ushort",
            "uuid" => "Guid",
            "object" => "JsonObject",
            "boolean" => "bool",
            "json" => "JsonNode",
            _ when manifest.Enums.Any(item => item.Name == typeName) => ToPascalCase(typeName),
            _ => ToPascalCase(typeName)
        };
    }

    private static string ToPascalCase(string identifier)
    {
        if (identifier.Contains('_', StringComparison.Ordinal))
        {
            var builder = new StringBuilder(identifier.Length);
            foreach (var part in identifier.Split('_', StringSplitOptions.RemoveEmptyEntries))
            {
                builder.Append(char.ToUpperInvariant(part[0]));
                if (part.Length > 1)
                {
                    builder.Append(part[1..]);
                }
            }

            return builder.ToString();
        }

        return char.ToUpperInvariant(identifier[0]) + identifier[1..];
    }

    private static string ToGeneratedText(List<string> lines)
    {
        while (lines.Count > 0 && string.IsNullOrEmpty(lines[^1]))
        {
            lines.RemoveAt(lines.Count - 1);
        }

        return string.Join('\n', lines) + '\n';
    }

    private sealed record ShapeDefinition(string Name, IReadOnlyList<ManifestFieldDefinition> Fields);
}

/// <summary>Represents the generated source texts for both target languages.</summary>
/// <param name="Cpp">The generated C++ source text.</param>
/// <param name="CSharp">The generated C# source text.</param>
public sealed record GeneratedModels(string Cpp, string CSharp);
